name: News
package-name: aldryn-news
url: https://github.com/aldryn/aldryn-news
author:
  name: Divio AG
  url: https://www.divio.ch
installed-apps:
  - aldryn_news
  - hvad
  - djangocms_text_ckeditor
  - django_select2
  - easy_thumbnails
  - filer
  - taggit
  - aldryn-search
version: 0.1.9
description: Publish news in django CMS
license:
  name: BSD
  text: !literal-include LICENSE.txt
